apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Madn676kOg+N4NW7v2XiyqaYPLCWLTkzafnnaWwRlcoFK/Ao1ubMRbUdhjaDXyf4i6jeGwc3uawlKBu/+wBcMU92omVJCxqaHOtjo61A+ghW7LLpfeHWq3GQrYnxdfwSzCEXNVAaehj/vzw1fZh/KebkwNpgzvV5dF6u0RbaN/KuV8+1AhCMhszCwaZdbr1p8HxoioKm86Y5O1ZngHq2r1HLtfdV75+07UYfYLnHmaEN+HuLHE41p6yLXlsVk63USeKurHCzVFZ4e2F0AbFCxg+EusNjEKZW3gXrusykWHvYrCAU0YhbEh+B7vI=,iv:Nb7NdWR0czAqMo1pSMsAZXjb3AHGG5Whaf+egNSJm40=,tag:zRwUvJdzd2sD16Gp1kuW2A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMazcvY29YMkhYQlVRVXJU
            MGFKN3NtL1VvMy9Wd2FTODB0eFVZZ2NEQm44CmhoVjBBRUpvQVU3ZWhWRlBsbklh
            MGRMZFFPU0VoOHZUNjBqcXRSb2JCUWsKLS0tIFBXeTR0RVRhWnM5dXFKb0JBNVZB
            SjMzdy9vT1JkMmhRQk5FRVJYcHQyWTQK8GO3jRvLuLjqAEr1Q2mY2uRxx2sjGbNC
            3WkUJvHu2wjMLpk4s/R+QG4aNQtF40gDLA4Id9pxV6QmdzJotnHOdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T07:32:05Z"
    mac: ENC[AES256_GCM,data:ZaFYjFD7Of69jhX9L2iAwS03BCYRmwvI8bvJbTwX5bfuyMoIqXLoJ7qBAApu96te7V/ANR/1fpT1nIMeaYv3LgJbiSbZDCYXBwmPO//1TxRUXAsy9CZ3PywGCMbZdtLy6NpSw0iV54MwuesP2Q/yzXl9xkBfW1eSJrlpcm3a/ws=,iv:e0YadSrUYGLxT0zxd7D4dVsNJlvo/KIasT9CyPAAYVE=,tag:Tk5FWtGJHXhhFCsGmcf8dQ==,type:str]
    version: 3.13.2
