apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # user node user ID
        runAsGroup: 101 # user node group ID
      containers:
        - name: website
          image: ghcr.io/lukadimnik/website:latest
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - { name: nginx-cache, mountPath: /var/cache/nginx }
            - { name: nginx-run, mountPath: /var/run }
      volumes:
        - { name: nginx-cache, emptyDir: {} }
        - { name: nginx-run, emptyDir: {} }

      restartPolicy: Always
