apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PUfmlFnHxTM=,iv:0S56TGWetYizBE2f5tN9hECuuE/Lqfip0hfNJafDv4I=,tag:48Ba5ywAFz0+dW+huN/HiA==,type:str]
    user: ENC[AES256_GCM,data:R7ylwvyfUho=,iv:12up6BBZtz7BJf1MbP2g5Tq+K/xSB1QR7Jf59xUUpNs=,tag:UWX0hWll0gWCM+nit/1jhQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUy92NDllR09UN0kyMlFz
            NG9CbDI3MUZranZHMEx0QkVQRzF2ckhjWGlBCjM0U0NralQ1TW9JVER2NWRjekdZ
            dnArdGtWdG1hNEhhNzdPUHpYYlBxcEEKLS0tIGtqTXFJNFpGRHU5WXpOZGN2WUh3
            KyttNkdpV2dQUm4wU2FrMmp4L2VzWHMKLMUYKmvh5VPRu6R8PVhjiCt0iZfSBrKL
            0XOmSHMKEUhAHwbZ59ewBGdqFnxbRb/gLa4afizCI+lTG1pM7jOv9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T18:36:35Z"
    mac: ENC[AES256_GCM,data:Uw/SKdxs7J3AqhKdurcvl/CA1hfrv7XHpVBWPFTkQ2+HfgN/ffA3aWTz3vTt+TigUNp1JBQeDjkqCKj1LYdbAYqy8BzhdbJEv+IG5jDLIGWU5dcWw1/IMgb0r3StWIkQDDYJA/8jGTZa+JdoeNAzCOKaOYAOaFMmmExQYeusOV8=,iv:tM4gvFb/MUm170NkXSs49dmOE2lTnhfmrjmgiQoombE=,tag:x9AyK4/cQevy+mFNbskaEw==,type:str]
    version: 3.13.1
