apiVersion: v1
data:
    AccountTag: ENC[AES256_GCM,data:lrlLD+jNrOA++SIQtUIKMhsd4G6of43Ka4ZGZGxImWE=,iv:bgpv1aKuwiboN6uT4MRlYA/l+DRjTcqJd1TrXTfsdKM=,tag:hnNql2Wh09i+lXhYpeT96w==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:TeDRj2f4eJ8oaUh16sBtd1BwrjVXFTVeeVBz8ozsfRHau9dPMgDG3A9/ITk=,iv:ix0gq1sanIFBhdQLEw6p2p3jA1IBtSLu0XceYsVD0wQ=,tag:ASNbn1Uh1+ttJDrbQUZMrw==,type:str]
    TunnelID: ENC[AES256_GCM,data:8ofFsP99XRDmDTJCMt1vokrVucBAc7qb6N/zeW3a7L/DoDxa,iv:W5k8agFwUGZkjMCeSCTfS+d16jmSXpoK4enfPlOkVS4=,tag:6DW0rcx7ab/vh3/IRO0Dcg==,type:str]
    Endpoint: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRlVVZUZFYWEzWnJmY1Fk
            eTUwM3JsMnJld1NsOVRkOVUwUXVldXFuMnhNCmU4Y0hQeGdGUVpMNlF1d2pkMFhK
            RFVCN2dBMUE2OUtwY3Q1TmFMN2FJTzgKLS0tIEh0Z1RlZEZGY2Q5KzlDa0pIWmhC
            ZnFIZEpYRkF6amV5cGtPaWxLcVM2TUkKgEqvisKWZABg8Uuf2qdvitzIGblJVyWY
            CwXOu2ky/jqtOWMsQtQl9Wfg5nHioVUQS1NX1A1CmRNIacI6qvcELw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T19:06:52Z"
    mac: ENC[AES256_GCM,data:XrNCrgCzWi5gfob/8qZY2pTR+eRd3q4bCHq4nojTNpHgO9lMTpJnUcV7ywH8Qybl2bLB93flrmfF3jEy+dGqNPAS/+FtCs03I6k5B7+SCe1Lur0CCtjzTY+ClnEwBNT2XeE+LFvMtiRjGof1xIDQ+/qDefYonMmwEG4qoBKZWwg=,iv:ZdlWNzEhFoO5DS2dVtS5j7GfwqoFPiYtg2F8LqNWqK4=,tag:vIiOmFFIKhG6K8wqxa3W+w==,type:str]
    version: 3.13.1
