apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:TFXLNBwt3pIzjRVh/ukv5Vzjv6EXOXgYB+0AmFTd/YSJulqN83Y7G5yjUc8GEqE6UnhqQQpN6yCtsMY12ZDAql0yAz6946cSuH3qSLx00YOzm6apPfe6MKL5JZEWNXJ0VUZWkOOlkQgRju2RBUODMzSE6GYmmz6l18OIFgk6mB0bW/qfFJ2os+0sIuj5nM3dSiBa+wsAF36ed1BERGjjbXpPhkpaiBU6IIao9e14tivYEY9wSFTWP3mml/6R5zW1J+dRBZWQl+E1xszfoCR7hmYbdXAOgpXdkd8hXf7wHgJEWVva0G0doN+B24Y=,iv:DtifRuJo5vyq9pwS4m9ZzOoR3LtPjEisjlQcG+e6lb4=,tag:GMPIGJgBN5P0VEtKAfJ57w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZkxpZExibUh4RmwvalJa
            R3NLd1pwNVdQY1QzcWNsRUpiUkQ5cTZYc1NNClArSzBsbW1XZ0VxekhWQ2NmRkJq
            MHNmUzNNaU1VVGcraEs1RWpBeUk2K2sKLS0tIHJBcFFoU1hTTXR1ZDM1R0N6bWk0
            TnIyb1ZCNmc4dXd2NG5HZXF2MFNXUmcKbzBvLjM6lcCCwSS+jrfaTpqmnQhqfYLg
            X49L/Wp69TTzU0Lv31Y1POPt9xcs5x2yKPVxraZR7iP4IeWHsJracQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:16:39Z"
    mac: ENC[AES256_GCM,data:YmkXxTpOG5hVPuN8JqidnNTNDByo89Oc06Ky+c5js/TJzx+YSpUnFJSXQHic1cmylUgAqpG+TA6I8ZGBwM3KG6l55rkToNV9VAAQUq5dpQencwx0a4cb9ElTLwzk+wMZepuSJtK6kteHl+aEM5YIc+OLgm2BEoSFq6ZUkhNrYbA=,iv:1nhXodtv7Me8eU3lWL7NMN3YumrQktQNodHgYQtsA8Q=,tag:itAyCgKZ83ZChLWfHHN9sA==,type:str]
    version: 3.13.1
