apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:VZ+m2VEAV2Nbhu97P/9fD3h0qhx+KPwugSk1aYuhiYPlGTtXQtRIf6VgIBXoLkYcJ4ToeZ9r1VTOaYJYB8z0YcerIk8J7JqETj6Pame8hTv+72SY5dSVx/MPpQdeBBkT/SJhD+jgYEljzlzrEb53EsHLOSa1lcrtPWzByAyEEnEkycrLFsjxp89l0pLvnlw9qJMANeeFSX5Vb/74I6okJTfv2IxQToojNRZiw1plubv7DGLI+dJr3dcq2GM+FZbnvD3mMcC6ewGsqkMirGpg1huBcr/M6WsPlZMn7+Jaz2cjsjFSacq09N4a4gU=,iv:j5c2Z1F+yMvCkAVW3DPNpgTbUF0KuTBM1JVue2Et7xk=,tag:ZP0x67A+aQlbuIxXjlVKyw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2M2M1VlJEVkxaa1hYYUZ6
            Z09nc3JvR0FGMEVTQ09FRXlNSUR6YUdIMEhNCmF4VXp2SHh3NHhIRkFOejRVcyty
            MCtPQXNraSthN051TTUrNnVRdUhVVDgKLS0tIFpCKzN3MU1aZENjRGc3L0hoUjFh
            b3U0OEhDUU5YeG1jTXhFN0M5V3FzVGMKt+bGc6zGMDDW34dTpE7hnMxeSPetq1mV
            9mwtje3W7c6dh71CA42OtBqBs+DR+hQCCKXmqwxCkjjmpmL9ztVOKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T11:03:26Z"
    mac: ENC[AES256_GCM,data:MBuJyJ96qqIfKdKWI4XYwqqmDv8INYalb+jVkgpKUF1GPSBchdEenNNGEildRg/gluk3bn0praAbJbIqNG0ia/1shswyOdr3LSmNn6OiYVOWsmDpTV16HUa2k4wYYfBPXTSMcgauEBtF5lb5I3rWho3E6D0yUU6TptFIDfpvC0M=,iv:O/2PDLf7k5xW3B//EdlLAtaBX7PUkMdPourzPVPXK/I=,tag:EjuOurVOCFyBK3M7GPsW9w==,type:str]
    version: 3.13.2
