apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vNqZGeWcxwpCLzGsKEQgCDIu95MqGF5Csikr8oR2hwPv9E0Q/jH9p/9+D2H+O+Iy2ln6Ffgo9ao=,iv:75cpZ9sRl+5bmxHx6vDsDJSm2ODLtBGASQe/RyD3/bU=,tag:iWPF38kO8VgzlDEZcUc9vg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U3BGaVpUbW13OWloNmNK
            ZFBhVHFtbnQ0UW5LczNhOFJzYlhEbXFmeVZjCnNQUjdPdHNvMFIvbHFYUXB3bk5R
            VjZXUWlrQUpRQUdmKzg4NmhDSHJnZU0KLS0tIDZnejRsOC9YYWdZQ2FQcVZhdHNE
            eWllWGxiL0VRNkxLS3Q2aTBLbm5ZZkEK98/5K6OIO8ioPC0M1pj93Z6hW48krLCG
            wxad7sFFRaGEszDhK/O8kXeOapxkM+Z6lKQKyxHGkgjUgPJYGMDyUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0klae5fth9kw9s8gkycjmemr0l5y5rssm6vwzs7regh48vzxsdsyxhthd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:49:14Z"
    mac: ENC[AES256_GCM,data:ZCM4spFGWb5wfKRuHvZvx4JFz4Wh1ssIiM9rpAK5SnwfITvtEWgPh4AKcU3KfUtfL8vJiMBM1eIre8YBW8qVfeIyGaCJoQyzvGCkBQ9Z3rT20gR4pnMCUNvugYXwRSz194MN+zTK2TDyi4oh+6LmGazDTQuKz4KvUdYS3OZa+pI=,iv:FqaRkx3Q1gbFbkREHTaAtrwuB/9qV2NipyYQPBZx+7c=,tag:3nyzdDvFpQjotOEbHWEZ4g==,type:str]
    version: 3.13.2
